apiVersion: v1
kind: ConfigMap
metadata:
  name: behoerdenhelfer-config
  namespace: default
  labels:
    app: behoerdenhelfer
data:
  api_url: 'https://api.example.com'
  app_name: 'Behördenhelfer'
  app_version: 'v2.0.0'
  log_level: 'info'
